# Generated by Django 3.2.4 on 2021-06-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ID_Image', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Estofados Automotivos', 'Estofados Automotivos'), ('Sofas', 'Sofas'), ('Camas', 'Camas'), ('Carpetes e Tapetes', 'Carpetes e Tapetes')], max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
