# Generated by Django 3.2.8 on 2021-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('ID_Limpeza', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
    ]
