# Generated by Django 3.2.8 on 2021-10-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_limpeza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('limpeza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.limpeza')),
                ('ID_Automovel', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('core.limpeza',),
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('limpeza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.limpeza')),
                ('ID_Cama', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('core.limpeza',),
        ),
        migrations.CreateModel(
            name='Tapete',
            fields=[
                ('limpeza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.limpeza')),
                ('ID_Tapete', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('core.limpeza',),
        ),
    ]
