# Generated by Django 3.2.8 on 2021-10-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_depoimento_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('limpeza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.limpeza')),
                ('ID_Sofa', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('core.limpeza',),
        ),
    ]
