# Generated by Django 3.2.4 on 2021-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_image_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('ID_Sofa', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='categoria',
            field=models.CharField(choices=[('Sofas', 'Sofas'), ('Camas', 'Camas'), ('Carpetes e Tapetes', 'Carpetes e Tapetes'), ('Estofados Automotivos', 'Estofados Automotivos')], max_length=100),
        ),
    ]
