# Generated by Django 3.2.4 on 2021-06-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210617_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
