# Generated by Django 3.2.8 on 2021-10-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sofa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovel',
            options={'verbose_name_plural': 'Automoveis'},
        ),
    ]
