# Generated by Django 3.2.4 on 2021-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('ID_Automovel', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('ID_Cama', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tapede',
            fields=[
                ('ID_Tapete', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
    ]
