# Generated by Django 3.2.4 on 2021-06-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_automovel_cama_tapede'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tapede',
            new_name='Tapete',
        ),
    ]
