# Generated by Django 3.2.4 on 2021-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_depoimentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depoimentos',
            new_name='Depoimento',
        ),
    ]
