# Generated by Django 3.2.4 on 2021-06-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_depoimentos_depoimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('ID_Parceiros', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='depoimento',
            old_name='ID_Automovel',
            new_name='ID_Depoimento',
        ),
    ]
