# Generated by Django 3.2.4 on 2021-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210617_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parceiros',
            new_name='Parceiro',
        ),
        migrations.RenameField(
            model_name='parceiro',
            old_name='ID_Parceiros',
            new_name='ID_Parceiro',
        ),
    ]
